AllCops:
  DisabledByDefault: true
  TargetRubyVersion: 2.2

Style/IndentationWidth:
  Enabled: true

Style/HashSyntax:
  Enabled: true

Style/Semicolon:
  Enabled: true

Style/StringLiterals:
  Enabled: true

Style/StringLiteralsInInterpolation:
  Enabled: true

Style/TrailingWhitespace:
  Enabled: true
