name              'rvm'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Manages system-wide and per-user RVMs and manages installed Rubies via Chef Resources.'
version           '2.0.1'
source_url        'https://github.com/sous-chefs/rvm'
issues_url        'https://github.com/sous-chefs/rvm/issues'

chef_version      '>= 15.3'

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'oracle'
supports 'redhat'
supports 'scientific'
supports 'ubuntu'
