name              'rvm'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Manages system-wide and per-user RVMs and manages installed Rubies via Chef Resources.'
version           '2.0.10'
source_url        'https://github.com/sous-chefs/rvm'
issues_url        'https://github.com/sous-chefs/rvm/issues'

chef_version      '>= 15.3'

supports 'almalinux', '>= 8.0'
supports 'amazon', '>= 2023.0'
supports 'centos_stream', '>= 9.0'
supports 'debian', '>= 12.0'
supports 'fedora'
supports 'oracle', '>= 8.0'
supports 'redhat', '>= 8.0'
supports 'rocky', '>= 8.0'
supports 'ubuntu', '>= 22.04'
