# rvm loading hook
#
# Generated by Chef for <%= node[:fqdn] %>
# Local modifications will be overwritten.
#
if [ -s "${HOME}/.rvm/scripts/rvm" ]; then
  source "${HOME}/.rvm/scripts/rvm"
elif [ -s "/usr/local/lib/rvm" ]; then
  source "/usr/local/lib/rvm"
fi
